const clientType = {
    CHANGE_DATE_EVENT: "CHANGE_DATE_EVENT",
    GOTO_TODAY_EVENT: "GOTO_TODAY_EVENT",
    FETCHED_EVENT_LIST: "FETCHED_EVENT_LIST",
    SHOW_CONTROL_MODAL: "SHOW_CONTROL_MODAL",
    SHOW_EVENTLIST_MODAL: "SHOW_EVENTLIST_MODAL",

    HIDE_CONTROL_MODAL: "HIDE_CONTROL_MODAL",
    HIDE_EVENTLIST_MODAL: "HIDE_EVENTLIST_MODAL",

    SAVE_EVENT_SUCCESS: "SAVE_EVENT_SUCCESS",
    DELETE_EVENT_SUCCESS: "DELETE_EVENT_SUCCESS",
    SAVE_TO_LOCAL: "SAVE_TO_LOCAL",
    SET_BUTTON_DISABLE: "SET_BUTTON_DISABLE"
};

export default clientType;
